config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get "auth/google_oauth2/callback", to: "session#create"

  delete "sign_out", to: "session#destroy"

  resources :categories, :brands, except: [:show, :edit, :update]

  resources :storages, except: [:show]

  resources :issues, :employees, :admins

  resources :items do
    member do 
      get "document"
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      post "mark_as_read"
    end
  end

  get "notifications/clear/table", to: "notifications#clear_table"
end

app/views/admins/_form.html.erb
<%= form_for @admin do |a| %>
  <div class="form-group row mx-auto my-4">
    <%= a.label :name, class:"col-sm-1 col-form-label" %>
    <div class="col-sm-10">
      <%= a.text_field :name, required: true, class:"form-control" %>
    </div>
  </div>
  <div class="form-group row mx-auto my-4">
    <%= a.label :email, class:"col-1 col-form-label" %>
    <div class="col-sm-10">
      <%= a.text_field :email, required: true, class:"form-control" %>
    </div>
  </div>
  <div class="form-group mx-auto row my-4">
    <div class="col-4">
      <%= a.label :category_access, required: true %>
      <span class="ml-5"><%= a.select :category_access, [['Yes', true], ['No', false]] %></span>
    </div>
    <div class="col-4">
      <%= a.label :brand_access, required: true %>
      <span class="ml-5"><%= a.select :brand_access, [['Yes', true], ['No', false]] %></span>
    </div>
    <div class="col-4">
      <%= a.label :storage_access, required: true %>
      <span class="ml-5"><%= a.select :storage_access, [['Yes', true], ['No', false]] %></span>
    </div>
  </div>
  <div class="form-group mx-auto row my-4">
    <div class="col-6">
      <%= a.label :item_access, required: true %>
      <span class="ml-5"><%= a.select :item_access, [['Yes', true], ['No', false]] %></span>
    </div>
    <div class="col-6">
      <%= a.label :employee_access, required: true %>
      <span class="ml-5"><%= a.select :employee_access, [['Yes', true], ['No', false]] %></span>
    </div>
  </div>
  <div class="text-center my-4">
    <%= a.submit "Submit", class:"btn btn-primary" %>
  </div>
<%end%>

app/views/admins/edit.html.erb
<main class="container">
  <h3 class="text-center">Edit Storage Details</h3>
  <%= render "form" %>
</main>

app/views/admins/index.html.erb
<main class="container-fluid">
  <div class="text-center">
    <h3>Admins</h3>
  </div>
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Email ID</th>
      <th>Category</th>
      <th>Brand</th>
      <th>Item</th>
      <th>Employee</th>
      <th>Storage</th>
      <th>Admin</th>
    <tr>
    <% @admins.each do |a| %>
      <tr>
        <td><%= a.id %></td>
        <td><%= a.name %></td>
        <td><%= a.email %></td>
        <td>
          <% if a.category_access %>
            <%= "Yes" %>
          <% else %>
            <%= "No" %>
          <% end %>
        </td>
        <td>
          <% if a.brand_access %>
            <%= "Yes" %>
          <% else %>
            <%= "No" %>
          <% end %>
        </td>
        <td>
          <% if a.item_access %>
            <%= "Yes" %>
          <% else %>
            <%= "No" %>
          <% end %>
        </td>
        <td>
          <% if a.employee_access %>
            <%= "Yes" %>
          <% else %>
            <%= "No" %>
          <% end %>
        </td>
        <td>
          <% if a.storage_access %>
            <%= "Yes" %>
          <% else %>
            <%= "No" %>
          <% end %>
        </td>
        <td>
          <% if a.admin_access %>
            <%= "Yes" %>
          <% else %>
            <%= "No" %>
          <% end %>
        </td>
        <% if current_user && current_user.admin_access %>
          <td><%= link_to "Show", admin_path(a) %></td>
          <td><%= link_to "Edit", edit_admin_path(a) %></td>
          <td>
            <% unless a == current_user %>
              <%= link_to "Delete", admin_path(a), method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <div class="text-center">
    <% if current_user && current_user.admin_access %>
      <%= link_to "Add User", new_admin_path, class:"btn btn-primary my-5" %>
    <% end %>
  </div>
</main>

app/views/admins/new.html.erb
<main class="container">
  <h3 class="text-center">Add New Storage Details</h3>
  <%= render "form" %>
</main>