config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get "auth/google_oauth2/callback", to: "session#create"

  delete "sign_out", to: "session#destroy"

  resources :categories, :brands, except: [:show, :edit, :update]

  resources :storages, except: [:show]

  resources :issues, :employees, :admins

  resources :items do
    member do 
      get "document"
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      post "mark_as_read"
    end
  end

  get "notifications/clear/table", to: "notifications#clear_table"
end

app/models/notification.rb
class Notification < ApplicationRecord
  scope :unread_notification, -> { where(read_status: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :require_login

  def index
    @notifications_all = Notification.all
    @notifications = Notification.unread_notification
  end

  def mark_as_read
    @notifications = Notification.unread_notification
    @notifications.update_all(read_status: true)
    render json: { success: true }
  end

  def destroy
    if current_user && current_user.admin_access
      @notification = Notification.find(params[:id])
      @notification.destroy
      redirect_to notifications_path
    else
      redirect_to root_path
    end
  end

  def clear_table
    if current_user && current_user.admin_access
      @notifications = Notification.all
      @notifications.destroy_all
      redirect_to notifications_path
    else
      redirect_to root_path
    end
  end

  private
  def require_login
    unless current_user
      flash[:error] = "You must be logged in to access notification section"
      redirect_to root_path
    end
  end
end

app/views/notifications/index.html.erb
<main class="container">
  <div class="mt-3 mb-5">
    <% unless @notifications_all.blank? %>
      <div class="text-center mb-3">
        <%= link_to "Delete all", notifications_clear_table_path, data: {confirm: "Are you sure?"} %>
      </div>
      <div class="mb-4">
        <% @notifications_all.each do |n| %>
          <div class="my-2">The <%= n.notifiable_name %> <%= n.details %> 
            <% if current_user && current_user.employee_access %>
              <%= link_to "Delete", notification_path(n), method: :delete, data: {confirm: "Are you sure?"} %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      <h4 class="text-danger">There's no new notification.</h4>
    <% end %>
  </div>
</main>