config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  get "auth/google_oauth2/callback", to: "session#create"

  delete "sign_out", to: "session#destroy"

  resources :categories, :brands, except: [:show, :edit, :update]

  resources :storages, except: [:show]

  resources :issues, :employees, :admins

  resources :items do
    member do 
      get "document"
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      post "mark_as_read"
    end
  end

  get "notifications/clear/table", to: "notifications#clear_table"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :brands
  has_many :items, through: :brands
  has_one :storage
  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_login

  def index
    @categories = Category.all
  end

  def new
    if current_user && current_user.category_access
      @category = Category.new
    else
      redirect_to categories_path
    end
  end
  
  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to categories_path
    else
      flash[:message] = @category.errors.full_messages
      redirect_to new_category_path
    end
  end

  def destroy
    if current_user && current_user.category_access
      @category = Category.find(params[:id])
      if @category.brands.blank? && @category.storage.blank?
        @category.destroy
        redirect_to categories_path
      else
        redirect_to categories_path, notice: "Some brands and/or storage details belong to this category. Can't be deleted."
      end
    else
      redirect_to categories_path
    end
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_login
    unless current_user
      flash[:error] = "You must be logged in to access category section"
      redirect_to root_path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<main class="container-fluid">
<div class="text-center">
    <h3>Categories</h3>
  </div>
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Category Name</th>
    </tr>
    <% @categories.each do |c| %>
      <tr>
        <td><%= c.id %></td>
        <td><%= c.name %></td>
        <% if current_user && current_user.category_access %>
          <td><%= link_to "Delete", category_path(c), method: :delete, data: {confirm: "Are you sure?"} %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <div class="text-center">
    <% if current_user && current_user.category_access %>
      <%= link_to "New Category", new_category_path, class:"btn btn-primary my-5" %>
    <% end %>
  </div>
</main>

app/views/categories/new.html.erb
<main class="container">
  <h3 class="text-center">Add New Category Name</h3>
  <%= form_for @category do |c| %>
    <div class="form-group row mx-4 my-4">
      <%= c.label :name, class:"col-1 col-form-label font-weight-bold" %>
      <div class ="col-sm-10">
        <%= c.text_field :name, required: true, class:"form-control" %>
      </div>
    </div>
    <div class="text-center my-5">
      <%= c.submit "Submit", class:"btn btn-primary" %>
    </div>
  <% end %>
</main>